<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="happyface.jpg" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ResourceLibrary\ResourceLibrary.csproj">
      <Project>{6703377C-C1F6-42C0-A6B6-F6A97B2976B8}</Project>
      <Name>ResourceLibrary</Name>
    </ProjectReference>
  </ItemGroup>
    
</Project>



  