<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>    
  
  <ItemGroup>
    <ProjectReference Include="..\CustomControls\CustomControls.csproj">
      <Project>{98A994BA-5A6D-4E1B-BDF4-C1662C99CB1A}</Project>
      <Name>CustomControls</Name>
    </ProjectReference>
  </ItemGroup>  
</Project>